# Generated by Django 4.0.4 on 2022-04-18 22:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Область склада')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cargo_capacity', models.PositiveSmallIntegerField(help_text='Измеряется в тоннах', verbose_name='Макс. грузоподъемность')),
            ],
            options={
                'verbose_name': 'Модель грузовика',
                'verbose_name_plural': 'Модели грузовиков',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(max_length=100, verbose_name='Бортовой номер')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trucks.truckmodel')),
            ],
            options={
                'verbose_name': 'Грузовик',
                'verbose_name_plural': 'Грузовики',
                'unique_together': {('model', 'site_number')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnt', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Координаты выгрузки')),
                ('balance_before', models.PositiveSmallIntegerField(help_text='Измеряется в тоннах', verbose_name='Объем до разгрузки')),
                ('balance_after', models.PositiveSmallIntegerField(help_text='Измеряется в тоннах', verbose_name='Объем после разгрузки')),
                ('cargo_extras', models.JSONField(null=True, verbose_name='Доп. данные о грузе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.stock')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trucks.truck')),
            ],
            options={
                'verbose_name': 'Журнал разгрузки',
                'verbose_name_plural': 'Журнал разгрузки',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveSmallIntegerField(help_text='Измеряется в тоннах', verbose_name='текущий вес')),
                ('extras', models.JSONField(verbose_name='Доп.данные о грузе')),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck')),
            ],
            options={
                'verbose_name': 'Текущий груз грузовика',
                'verbose_name_plural': 'Текущий груз грузовиков',
            },
        ),
    ]
